name: CI

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Read value from Properties-file
    runs-on: ubuntu-latest
    steps:
      - id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version'
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          tags: thedeveloperden/devdenbot:${{ steps.read_property.outputs.value }}
          tag_with_ref: true
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && echo ${{ secrets.SERVER_PASSWORD }} | sudo -S git pull https://${{ secrets.TOKEN }}@github.com/<YOURGITHUBUSERNAME>/<NAMEOFYOURREPO>.git
