name: CI

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version'
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          repository: thedeveloperden/devdenbot
          tags: ${{ steps.read_property.outputs.value }}
          tag_with_ref: true
  deploy:
    needs: [ push_to_registry ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            docker stop devdenbot
            docker rm devdenbot
            docker run --name devdenbot --env SENTRY_DSN=${{ secrets.SENTRY_DSN }} --env DDB_TOKEN=${{ secrets.DDB_TOKEN }} --env DDB_DB_USERNAME=${{ secrets.DDB_DB_USERNAME }} --env DDB_DB_NAME=devden --env DDB_DB_PASSWORD=${{ secrets.DDB_DB_PASSWORD }} --env DDB_DB_HOST=${{ secrets.DDB_DB_HOST }} --mount source=devden,target=/var/data -d --restart unless-stopped ghcr.io/thedeveloperden/devdenbot
