# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew shadowJar
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: CapRover Deploy
      # You may pin to the exact commit or the version.
      # uses: AlexxNB/caprover-action@45fdf55f3213582285394908e8a3a0d2df41e21d
      uses: AlexxNB/caprover-action@v1
      with:
        # CapRover admin panel URL. Ex. https://captain.root.domain.com
        server: https://captain.bristermitten.me
      # CapRover admin password. Use $\{{ secrets.CAPROVER_PASSWORD }} for better security.
        password:  ${{ secrets.CAPROVER_PASSWORD }}
    # Application name on the CapRover server. Must exists.
        appname: devdenbot2
          
          
